# syntax=docker/dockerfile:1.7
FROM node:22-bookworm

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y \
    chromium \
    tini \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

ENV NODE_ENV=development

WORKDIR /app

RUN mkdir -p /app/node_modules && chown -R node:node /app

USER node

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["sleep", "infinity"]